name: Manual Test

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:42

    defaults:
      run:
        shell: /bin/bash
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Essential Tools
        run: dnf install -y dnf-plugins-core redhat-rpm-config rpm-build rpmdevtools rpmlint

      - name: Setup Build Environment
        run: rpmdev-setuptree

      - name: Download Source Tarball
        run: spectool -g -a -R looking-glass.spec

      - name: Install Build Dependencies
        run: dnf builddep -y --spec looking-glass.spec

      - name: Build Packages
        run: rpmbuild -ba looking-glass.spec

